create table schedules (
ID INT PRIMARY KEY NOT NULL,
VOLUME_ID TEXT(64) NOT NULL,
MON INT NONT NULL, 
TUE INT NONT NULL, 
WED INT NONT NULL, 
THU INT NONT NULL, 
FRI INT NONT NULL, 
SAT INT NONT NULL, 
SUN INT NONT NULL, 
HOUR INT NONT NULL, 
MINUTE INT NONT NULL, 
DESC TEXT,
PERIOD_TO_KEEP INT,
NUMBER_OF_KEEP INT,
STATUS TEXT NOT NULL);

